Repository smosco/react-player-plugin-prompter, pull requests merged in 2024-11, with the labels that each got.

#26 feat: TextDisplay, LineView, BlockView에 제네릭 타입을 추가하여 사용자 정의 타입을 지원할 수 있도록 수정
  core/dist/components/BlockView.d.ts
  core/dist/components/BlockView.d.ts.map
  core/dist/components/LineView.d.ts
  core/dist/components/LineView.d.ts.map
  core/dist/components/ReactScriptPlayer.d.ts
  core/dist/components/ReactScriptPlayer.d.ts.map
  core/dist/components/TextDisplay.d.ts
  core/dist/components/TextDisplay.d.ts.map
  core/dist/index.js
  core/dist/index.js.map
  core/dist/interfaces/Scripts.d.ts
  core/dist/interfaces/Scripts.d.ts.map
  core/dist/utils/findCurrentScriptIndex.d.ts
  core/dist/utils/findCurrentScriptIndex.d.ts.map
  core/dist/utils/findCurrentSubtitleIndex.d.ts
  core/dist/utils/findCurrentSubtitleIndex.d.ts.map
  core/src/components/BlockView.tsx
  core/src/components/LineView.tsx
  core/src/components/ReactScriptPlayer.module.scss
  core/src/components/ReactScriptPlayer.tsx
  core/src/components/TextDisplay.tsx
  core/src/interfaces/Scripts.ts
  core/src/utils/findCurrentScriptIndex.ts
  core/src/utils/findCurrentSubtitleIndex.ts
  demo/src/App.tsx
  demo/src/components/ScriptOption.module.scss
  demo/src/components/ScriptOption.tsx
  demo/src/interfaces/Scripts.ts
  demo/src/mocks/scriptsMockData.ts
  demo/src/mocks/subtitleMockData.ts
Labels: feat, refactor, fix

#27 chore: main에 머지되면 바로 npm에 배포가 되도록 액션 스크립트 추가
  .github/workflows/publish.yml
Labels: chore

#31 [feat] isAsync에 따라 동영상 재생 동기화 안 되게 설정하는 코드 구현. 현재는 Blockview만 구현
  .pnp.cjs
  core/dist/components/BlockView.d.ts
  core/dist/components/BlockView.d.ts.map
  core/dist/components/LineView.d.ts
  core/dist/components/LineView.d.ts.map
  core/dist/components/ReactScriptPlayer.d.ts.map
  core/dist/hooks/useThrottling.d.ts
  core/dist/hooks/useThrottling.d.ts.map
  core/dist/index.js
  core/dist/index.js.map
  core/dist/utils/findClickedIndex.d.ts
  core/dist/utils/findClickedIndex.d.ts.map
  core/dist/utils/moveToScriptAtIndex.d.ts
  core/dist/utils/moveToScriptAtIndex.d.ts.map
  core/src/components/BlockView.tsx
  core/src/components/LineView.tsx
  core/src/components/ReactScriptPlayer.tsx
  core/src/hooks/useThrottling.ts
  core/src/utils/findClickedIndex.ts
  core/src/utils/moveToScriptAtIndex.ts
  package.json
Labels: feat

#34 [feat] 자막 가운데 정렬 버튼 switch버튼 구현
  core/dist/components/BlockView.d.ts
  core/dist/components/BlockView.d.ts.map
  core/dist/components/ReactScriptPlayer.d.ts.map
  core/dist/components/SwitchButton.d.ts
  core/dist/components/SwitchButton.d.ts.map
  core/dist/components/SwithButton.d.ts
  core/dist/components/SwithButton.d.ts.map
  core/dist/index.js
  core/dist/index.js.map
  core/dist/utils/findClickedIndex.d.ts
  core/dist/utils/findClickedIndex.d.ts.map
  core/src/components/BlockView.tsx
  core/src/components/ReactScriptPlayer.module.scss
  core/src/components/ReactScriptPlayer.tsx
  core/src/components/SwitchButton.tsx
  core/src/utils/findClickedIndex.ts
Labels: feat, design

#36 feat : switch버튼을 focus 버튼으로 변경
  core/dist/components/BlockView.d.ts
  core/dist/components/BlockView.d.ts.map
  core/dist/components/ReactScriptPlayer.d.ts
  core/dist/components/ReactScriptPlayer.d.ts.map
  core/dist/index.js
  core/dist/index.js.map
  core/src/components/BlockView.tsx
  core/src/components/ReactScriptPlayer.module.scss
  core/src/components/ReactScriptPlayer.tsx
  core/src/components/SwitchButton.tsx
  demo/src/App.tsx
  demo/src/components/VideoPlayer.module.scss
Labels: feat, refactor, design

#38 fix : 렌더링 너무 자주해와서 버튼이 안 눌렸던 문제 해결
  core/dist/components/BlockView.d.ts.map
  core/dist/components/LineView.d.ts.map
  core/dist/components/SwitchButton.d.ts
  core/dist/components/SwitchButton.d.ts.map
  core/dist/components/SwithButton.d.ts
  core/dist/components/SwithButton.d.ts.map
  core/dist/hooks/useThrottling.d.ts.map
  core/dist/index.js
  core/dist/index.js.map
  core/src/components/LineView.tsx
  core/src/hooks/useThrottling.ts
  core/src/utils/findCurrentScriptIndex.ts
  demo/src/App.tsx
Labels: fix

#40 chore: write README file and setup CI/CD for npm auto-publish
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/publish.yml
  .pnp.cjs
  .prettierignore
  LICENSE
  README.md
  core/README.md
  core/package.json
Labels: chore
