Repository smosco/react-player-plugin-prompter, pull requests merged in 2024-10, with the labels that each got.

#2 feat : 기존 라이브러리, 데모 애플리케이션 코드를 모노레포로 이전하고 esbuild의 scss및 svg 적용 안되던 문제 해결
  .pnp.cjs
  core/dist/components/BlockView.d.ts
  core/dist/components/BlockView.d.ts.map
  core/dist/components/LineView.d.ts
  core/dist/components/LineView.d.ts.map
  core/dist/components/ReactScriptPlayer.d.ts
  core/dist/components/ReactScriptPlayer.d.ts.map
  core/dist/components/TextDisplay.d.ts
  core/dist/components/TextDisplay.d.ts.map
  core/dist/index.d.ts
  core/dist/index.d.ts.map
  core/dist/index.js
  core/dist/index.js.map
  core/dist/interfaces/Scripts.d.ts
  core/dist/interfaces/Scripts.d.ts.map
  core/dist/utils/convertTime.d.ts
  core/dist/utils/convertTime.d.ts.map
  core/esbuild.config.js
  core/package.json
  core/src/assets/icons/arrow_back.svg
  core/src/assets/icons/arrow_forward.svg
  core/src/components/BlockView.tsx
  core/src/components/LineView.tsx
  core/src/components/ReactScriptPlayer.module.scss
  core/src/components/ReactScriptPlayer.tsx
  core/src/components/TextDisplay.tsx
  core/src/global.d.ts
  core/src/index.ts
  core/src/interfaces/Scripts.ts
  core/src/utils/convertTime.ts
  core/tsconfig.json
  demo/package.json
  demo/src/App.tsx
  demo/src/components/ContorlBar.module.scss
  demo/src/components/ControlBar.tsx
  demo/src/components/SubtitleOption.module.scss
  demo/src/components/SubtitleOption.tsx
  demo/src/components/VideoPlayer.tsx
  demo/src/components/VideoWrapper.tsx
  demo/src/global.d.ts
  demo/src/hooks/useBooleanState.ts
  demo/src/interfaces/Scripts.ts
  demo/src/mocks/mockUrl.ts
  demo/src/mocks/subtitleMockData.ts
  demo/src/utils/formatTime.ts
  yarn.lock
Labels: feat, chore, fix

#5 feat : 재생 시간에 맞는 자막 동기화 및 현재 재생 자막 하이라이트 기능 추가
  core/dist/components/BlockView.d.ts
  core/dist/components/BlockView.d.ts.map
  core/dist/components/LineView.d.ts
  core/dist/components/LineView.d.ts.map
  core/dist/components/ReactScriptPlayer.d.ts
  core/dist/components/ReactScriptPlayer.d.ts.map
  core/dist/components/TextDisplay.d.ts.map
  core/dist/index.js
  core/dist/index.js.map
  core/src/components/BlockView.tsx
  core/src/components/LineView.tsx
  core/src/components/ReactScriptPlayer.module.scss
  core/src/components/ReactScriptPlayer.tsx
  core/src/components/TextDisplay.tsx
  demo/src/App.tsx
  demo/src/main.tsx
  demo/src/mocks/mockUrl.ts
  demo/src/mocks/subtitleMockData.ts
Labels: feat

#8 feat : 동영상배속버튼 추가
  demo/src/App.tsx
  demo/src/components/ControlBar.tsx
  demo/src/components/VideoPlayer.module.scss
Labels: feat

#10 refactor : 컨트롤바 코드 리팩토링
  demo/src/App.tsx
  demo/src/components/ControlBar.tsx
  demo/src/components/VideoPlayer.module.scss
Labels: feat, refactor

#12 chore : npm에 배포하기 전에 core의 패키지 name 변경
  .pnp.cjs
  .pnp.loader.mjs
  core/.npmignore
  core/esbuild.config.js
  core/package.json
  demo/package.json
  demo/src/App.tsx
  package.json
  yarn.lock
Labels: chore

#14 feat : 자막 컴포넌트 스타일을 외부에서 주입할 수 있도록 props 추가
  core/dist/components/BlockView.d.ts
  core/dist/components/BlockView.d.ts.map
  core/dist/components/LineView.d.ts
  core/dist/components/LineView.d.ts.map
  core/dist/components/ReactScriptPlayer.d.ts
  core/dist/components/ReactScriptPlayer.d.ts.map
  core/dist/components/TextDisplay.d.ts
  core/dist/components/TextDisplay.d.ts.map
  core/dist/hooks/useThrottling.d.ts
  core/dist/hooks/useThrottling.d.ts.map
  core/dist/index.d.ts
  core/dist/index.d.ts.map
  core/dist/index.js
  core/dist/index.js.map
  core/dist/utils/findCurrentSubtitleIndex.d.ts
  core/dist/utils/findCurrentSubtitleIndex.d.ts.map
  core/src/components/BlockView.tsx
  core/src/components/Button.tsx
  core/src/components/LineView.tsx
  core/src/components/ReactScriptPlayer.module.scss
  core/src/components/ReactScriptPlayer.tsx
  core/src/components/TextDisplay.tsx
  core/src/hooks/useThrottling.ts
  core/src/index.ts
  core/src/utils/findCurrentSubtitleIndex.ts
  demo/src/App.tsx
  demo/src/components/VideoPlayer.module.scss
  demo/src/mocks/mockUrl.ts
  demo/src/mocks/subtitleMockData.ts
Labels: feat

#16 chore : 한개씩 넘겨주던 style props객체로 분리
  .pnp.cjs
  .pnp.loader.mjs
  core/dist/components/BlockView.d.ts
  core/dist/components/BlockView.d.ts.map
  core/dist/components/Button.d.ts
  core/dist/components/Button.d.ts.map
  core/dist/components/LineView.d.ts
  core/dist/components/LineView.d.ts.map
  core/dist/components/ReactScriptPlayer.d.ts
  core/dist/components/ReactScriptPlayer.d.ts.map
  core/dist/components/TextDisplay.d.ts
  core/dist/components/TextDisplay.d.ts.map
  core/dist/index.js
  core/dist/index.js.map
  core/dist/interfaces/Scripts.d.ts
  core/dist/interfaces/Scripts.d.ts.map
  core/src/components/BlockView.tsx
  core/src/components/LineView.tsx
  core/src/components/ReactScriptPlayer.tsx
  core/src/components/TextDisplay.tsx
  core/src/hooks/useThrottling.ts
  core/src/interfaces/Scripts.ts
  demo/src/App.tsx
  package.json
Labels: chore, refactor

#18 [chore] yarn 버전 4.3.1로 고정
  .yarn/releases/yarn-4.3.1.cjs
  .yarnrc.yml
Labels: chore

#20 19 chore add parallel command to run core demo docs at once
  .eslintrc.json
  core/dist/index.js
  package.json
Labels: chore

#22 feat : 스크립트에 하이라이트 속성 추가 및 하이라이트 처리
  .pnp.cjs
  .pnp.loader.mjs
  core/dist/components/BlockView.d.ts.map
  core/dist/components/TextDisplay.d.ts.map
  core/dist/index.js
  core/dist/index.js.map
  core/dist/interfaces/Scripts.d.ts
  core/dist/interfaces/Scripts.d.ts.map
  core/src/components/ReactScriptPlayer.module.scss
  core/src/components/TextDisplay.tsx
  core/src/interfaces/Scripts.ts
  demo/src/interfaces/Scripts.ts
  demo/src/mocks/subtitleMockData.ts
  package.json
Labels: feat
